server:
  port: 8080

spring:
  application:
    name: SummerHackaton
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://svc.sel5.cloudtype.app:32076/summerhackathon?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
#    url: jdbc:mariadb://localhost:3316/summerhackathon?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC

    username: root
    password: Ieejhyeon03167#

  jpa:
    database: mysql

    generate-ddl: true

    ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
