
spring:
  application:
    name: SummerHackaton
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://svc.sel5.cloudtype.app:32076/summerhackathon

    username: root
    password: Ieejhyeon03167#

  jpa:
    database: mysql

    generate-ddl: true

    ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
